name: Build base python docker images
run-name: ${{ github.actor }}
on: [ push ]
jobs:
  build-and-upload-package:
    runs-on: [self-hosted, linux]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.8'
          architecture: 'x64'

      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel twine

      - name: Build package
        run: python setup.py bdist_wheel --universal

      - name: Upload package
        run: twine upload --repository-url https://gitlab.com/api/v4/projects/54080196/packages/pypi -u ci-python-package-user -p glpat-3zqVQwKxwU_Qsvc_8fw8 dist/*

